//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.MSMQServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Contract.IMsmqService", ConfigurationName="MSMQServiceReference.ContractIMsmqService")]
    public interface ContractIMsmqService {
        
        // CODEGEN: Generating message contract since the operation StartProcess is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Contract.IMsmqService/StartProcess")]
        void StartProcess(ConsoleApplication1.MSMQServiceReference.StartProcess request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcess {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Contract", Order=0)]
        public Contract.AnnounceRequest AnnounceRequest;
        
        public StartProcess() {
        }
        
        public StartProcess(Contract.AnnounceRequest AnnounceRequest) {
            this.AnnounceRequest = AnnounceRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContractIMsmqServiceChannel : ConsoleApplication1.MSMQServiceReference.ContractIMsmqService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractIMsmqServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.MSMQServiceReference.ContractIMsmqService>, ConsoleApplication1.MSMQServiceReference.ContractIMsmqService {
        
        public ContractIMsmqServiceClient() {
        }
        
        public ContractIMsmqServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractIMsmqServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractIMsmqServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractIMsmqServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ConsoleApplication1.MSMQServiceReference.ContractIMsmqService.StartProcess(ConsoleApplication1.MSMQServiceReference.StartProcess request) {
            base.Channel.StartProcess(request);
        }
        
        public void StartProcess(Contract.AnnounceRequest AnnounceRequest) {
            ConsoleApplication1.MSMQServiceReference.StartProcess inValue = new ConsoleApplication1.MSMQServiceReference.StartProcess();
            inValue.AnnounceRequest = AnnounceRequest;
            ((ConsoleApplication1.MSMQServiceReference.ContractIMsmqService)(this)).StartProcess(inValue);
        }
    }
}
